### ISSUE TITLE
Small help needed.

### ISSUE THREAD

**Issue by avicoder** [SkyLined/Bugs#1]
Hi, 

When you say "**Here's what happens next with paged heap enabled**" , Please elaborate more there.
I refer this document to get the fundamentals clear but it didn't help me much -  (https://msdn.microsoft.com/en-us/library/windows/hardware/ff543097(v=vs.85).aspx)

Can you also provide the command you'd used or brief walkthrough. 

I tried this- 
`gflags /p /enable iexplore.exe /full`
`ntsd -g -x iexplore.exe /CorruptAfterEnd`

Thanks

**Comment by SkyLined** [comment]
You may want to use this script that is part of BugId:
https://github.com/SkyLined/BugId/blob/master/PageHeap-MSIE.cmd

Just run "PageHeap-MSIE.cmd ON" to enable page heap in MSIE :)

(You will also need https://github.com/SkyLined/BugId/blob/master/PageHeap.cmd)

**Comment by SkyLined** [comment]
Oh, and sorry I don't have time to walk you through it step by step :(. If there is anything specific you don't understand, I can answer more precise questions. Otherwise: maybe if you look at many different bugs, it'll start to make sense to you - that's how I learned :) Good luck!

**Comment by avicoder** [comment]
Thanks.
I'll check BugId to troubleshoot issues I am facing.
BTW I'm not in hurry to use these tools right away, just wanted to make my fundamentals clear first.
Any references other than reading the previous reports (which I do a lot) would be helpful.
:)
